// <auto-generated />
namespace Milton.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AuthNumberOptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuthNumberOptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201607230802052_AuthNumberOptional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
