// <auto-generated />
namespace Milton.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BorderTrips_Sent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BorderTrips_Sent));
        
        string IMigrationMetadata.Id
        {
            get { return "201702150531069_BorderTrips_Sent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
